import type { Metadata } from "next";
import { Cinzel, Roboto } from "next/font/google";

import QueryProvider from "@/providers/query-provider";

import Header from "@/components/header";
import "./globals.css";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body
          className={`${cinzel.variable} ${roboto.variable} antialiased`}
        >
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </QueryProvider>
  );
}
